"""initial schema

Revision ID: b630b777a2b4
Revises: 
Create Date: 2026-08-10 14:16:49.537175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b630b777a2b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('inputs_used', sa.JSON(), nullable=False),
    sa.Column('deterministic_outputs', sa.JSON(), nullable=False),
    sa.Column('ai_output_summary', sa.Text(), nullable=False),
    sa.Column('advisor_action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_client_id'), 'audit_log', ['client_id'], unique=False)
    op.create_table('clients',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=False),
    sa.Column('goal_year', sa.Integer(), nullable=False),
    sa.Column('annual_contribution', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('cash_account_type', sa.String(), nullable=False),
    sa.Column('target_allocation', sa.JSON(), nullable=False),
    sa.Column('accounts_note', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('target_retirement_amount', sa.Float(), nullable=True),
    sa.Column('holdings_source', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.String(), nullable=True),
    sa.Column('trade_decisions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=True)
    op.create_table('strategies',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('target_allocation', sa.JSON(), nullable=False),
    sa.Column('rebalancing_threshold_pct', sa.Float(), nullable=False),
    sa.Column('typical_holdings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('msg_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('flagged_for_report', sa.Boolean(), nullable=False),
    sa.Column('flagged_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'msg_id', name='uq_chat_message_client_msg')
    )
    op.create_index(op.f('ix_chat_messages_client_id'), 'chat_messages', ['client_id'], unique=False)
    op.create_table('chat_state',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('exploratory_context_injected', sa.Boolean(), nullable=False),
    sa.Column('exploratory_context', sa.Text(), nullable=True),
    sa.Column('exploratory_context_captured_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('holdings_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis_per_share', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.String(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_lots_client_id'), 'holdings_lots', ['client_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('currency_display', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_holdings_lots_client_id'), table_name='holdings_lots')
    op.drop_table('holdings_lots')
    op.drop_table('chat_state')
    op.drop_index(op.f('ix_chat_messages_client_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_log_client_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
